# Generated by Django 6.0.4 on 2026-05-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
