# Generated by Django 6.0.4 on 2026-06-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_profile_created_at_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codehistory',
            name='user',
        ),
        migrations.AlterField(
            model_name='codehistory',
            name='output',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
